source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
platform :ios, '13.0'

flutter_application_path = '../flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'BoostTestIOS' do
  use_frameworks!
  install_all_flutter_pods(flutter_application_path)
  # 其他的pod库
  pod 'Masonry'
end

post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end